<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>


  <ItemGroup>
    <SupportedPlatform Include="browser" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="10.0.11" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Base\" />
    <Folder Include="Components\" />
    <Folder Include="Forms\" />
    <Folder Include="Grid\" />
    <Folder Include="Models\" />
    <Folder Include="Extensions\" />
    <Folder Include="Validation\" />
    <Folder Include="Services\" />
    <Folder Include="wwwroot\css\" />
    <Folder Include="wwwroot\js\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SecNetCore\SecNetCore.csproj" />
  </ItemGroup>

</Project>
